version: "3.8"
services:
  wordpress:
    build: .
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M
    restart: always
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: always
    networks:
      - internal

volumes:
  wordpress_data:
  db_data:


networks:
  internal:
    driver: bridge
