version: "3.8"
services:
  wordpress:
    build: .
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      PHP_MEMORY_LIMIT: 512M
      UPLOAD_MAX_FILESIZE: 128M
      POST_MAX_SIZE: 128M
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M
    restart: always
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/wp-login.php" ]
      interval: 20s
      timeout: 10s
      retries: 10

  db:
    platform: linux/amd64
    image: mysql:5.7.34
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: always

volumes:
  wordpress_data:
  db_data:
